name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: NUnit Tests
      working-directory: ICT3101_Calculator.UnitTests/
      run: dotnet test
    - name: SpecFLow Tests
      working-directory: SpecFlowCalculatorTests/
      run: dotnet test
