name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
      
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Create MagicNumbers.txt
      working-directory: ICT3101_Calculator.UnitTests/
      run: echo "CD .."
      run: cd ..
      run: echo "CD .."
      run: cd ..
      run: echo "Lab01"
      run: cd lab01
      run: echo "1\n2\n3\n4\n5" >> MagicNumbers.txt
      run: cat MagicNumbers.txt
    - name: NUnit Tests
      working-directory: ICT3101_Calculator.UnitTests/
      run: dotnet test
    - name: SpecFlow Tests
      working-directory: SpecFlowCalculatorTests/
      run: dotnet test
